### PR TITLE
Improve halo rendering

### PR DESCRIPTION
**Pull request by MattJeanes**
Should stop render.RenderView breaking constantly, now restricted to when powers are in use. Should also slightly improve performance.

### CODE REVIEW

**Comment by MattJeanes** [comment]
Have you implemented this change in your version 1.1?

**Comment by Metamorphics** [comment]
Yes

**Comment by Metamorphics** [comment]
I'm still trying to figure out how to work github. lol. Does this need to be applied to green lantern too? I'm an idiot. I'll apply it to green lantern in the next bug fix. I hate myself. I'm still figuring out how to use github.

**Comment by MattJeanes** [comment]
Cool no problem man

**Pull request closed without merging**
